export const AGREGAR_PRODUCTO = "AGREGAR_PRODUCTO";
export const AGREGAR_PRODUCTO_EXITO = "AGREGAR_PRODUCTO_EXITO";
export const AGREGAR_PRODUCTO_ERROR = "AGREGAR_PRODUCTO_ERRROR";

export const OBTENER_PRODUCTOS = "OBTENER_PRODUCTOS";
export const OBTENER_PRODUCTOS_EXITO = "OBTENER_PRODUCTOS_EXITO";
export const OBTENER_PRODUCTOS_ERROR = "OBTENER_PRODUCTOS_ERROR";

export const ELIMINAR_PRODUCTO = "ELIMINAR_PRODUCTO";
export const ELIMINAR_PRODUCTO_EXITO = "ELIMINAR_PRODUCTO_EXITO";
export const ELIMINAR_PRODUCTO_ERROR = "ELIMINAR_PRODUCTO_ERROR";

export const OBTENER_PRODUCTO_EDITAR = "OBTENER_PRODUCTO_EDITAR";
export const COMENZAR_EDICION_PRODUCTO = "COMENZAR_EDICION_PRODUCTO";
export const PRODUCTO_EDITAR_EXITO = "PRODUCTO_EDITAR_EXITO";
export const PRODUCTO_EDITAR_ERROR = "PRODUCTO_EDITAR_ERROR";

export const MOSTRAR_ALERTA = "MOSTRAR_ALERTA";
export const OCULTAR_ALERTA = "OCULTAR_ALERTA";
